# Generated by Django 4.0.5 on 2022-06-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awapp', '0005_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
