# Generated by Django 4.0.5 on 2022-06-12 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awapp', '0006_alter_post_img_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
