# Generated by Django 4.0.5 on 2022-06-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awapp', '0008_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='usability',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
